---
name: Release
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the package to release'
        required: true
      version:
        description: 'The version to release'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies
        run: bash scripts/deps.sh
      - name: Creating build user
        run: bash scripts/user.sh
      - name: Running tests
        run: bash scripts/test.sh "${{ github.event.inputs.name }}"
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies
        run: bash scripts/deps.sh
      - name: Creating build user
        run: bash scripts/user.sh
      - name: Updating PKGBUILD
        run: |
          bash scripts/update.sh inko "${{ github.event.inputs.version }}"
      - name: Updating AUR repository
        run: |
          bash scripts/aur.sh inko \
            "${{ github.event.inputs.version }}" \
            "${{ secrets.AUR_SSH_KEY }}"
