---
name: Release
run-name: |
  Release ${{ inputs.name }} v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the package to release'
        required: true
      version:
        description: 'The version to release'
        required: true

jobs:
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/aur:main
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Updating permissions
        run: setfacl -R -m u:build:rwx .
      - name: Updating PKGBUILD
        run: |
          bash scripts/update.sh "${{ inputs.name }}" "${{ inputs.version }}"
      - name: Updating AUR repository
        run: |
          bash scripts/aur.sh "${{ inputs.name }}" "${{ inputs.version }}" \
            "${{ secrets.AUR_SSH_KEY }}"
