---
name: Release
run-name: |
  Release ${{ github.events.inputs.name }} v${{ github.events.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the package to release'
        required: true
      version:
        description: 'The version to release'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/aur:main
    steps:
      - uses: actions/checkout@v4
      - name: Updating permissions
        run: setfacl -R -m u:build:rwx .
      - name: Running tests
        run: bash scripts/test.sh "${{ github.event.inputs.name }}"
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/aur:main
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Updating permissions
        run: setfacl -R -m u:build:rwx .
      - name: Updating PKGBUILD
        run: |
          bash scripts/update.sh inko "${{ github.event.inputs.version }}"
      - name: Updating AUR repository
        run: |
          bash scripts/aur.sh inko \
            "${{ github.event.inputs.version }}" \
            "${{ secrets.AUR_SSH_KEY }}"
